# Generated by Django 2.1 on 2018-12-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='region',
            new_name='store_region',
        ),
    ]
