# Generated by Django 2.1 on 2018-11-15 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, unique=True, verbose_name='Key')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Ключ Реєстраці',
                'verbose_name_plural': 'Ключі Реєстрації',
            },
        ),
    ]
