# Generated by Django 2.1 on 2018-11-15 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створений')),
                ('assortment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='Асортимент')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Назва')),
                ('status', models.CharField(blank=True, max_length=256, verbose_name='Статус')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ReportData', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'Товар - Звіт',
                'verbose_name_plural': 'Товари - Звіт',
            },
        ),
    ]
