# Generated by Django 2.1 on 2018-12-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181206_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='t_delta',
            field=models.CharField(max_length=128, verbose_name='Тривалість роботи'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='t_finish',
            field=models.CharField(max_length=128, verbose_name='Кінець роботи'),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='t_start',
            field=models.CharField(max_length=128, verbose_name='Початок роботи'),
        ),
    ]
