# Generated by Django 2.1 on 2018-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportdata_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='assortment_info',
            field=models.SmallIntegerField(null=True, verbose_name='Наявність асортименту у %'),
        ),
    ]
