# Generated by Django 2.1 on 2018-11-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportdata_assortment_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdata',
            old_name='assortment_info',
            new_name='assortment_percent',
        ),
    ]
