# Generated by Django 2.1 on 2018-11-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181119_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='status',
            field=models.BooleanField(verbose_name='Знайдено?'),
        ),
    ]
