# Generated by Django 2.1 on 2019-01-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportitem_goods_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitem',
            name='goods_item',
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_item', to='goods.Goods', verbose_name='Товар'),
        ),
    ]
