# Generated by Django 2.1 on 2019-01-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20190125_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportitem',
            old_name='name',
            new_name='goods_item',
        ),
    ]
