# Generated by Django 2.1 on 2018-11-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181125_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assortment', to='report.ReportData', verbose_name='Звіт'),
        ),
    ]
