# Generated by Django 2.1 on 2019-01-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_last_visited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_auto_20181206_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
                ('agent_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_store', to='store.Store', verbose_name='Торгова точка')),
            ],
            options={
                'verbose_name': 'Агенти - Торгові точки',
            },
        ),
        migrations.RemoveField(
            model_name='route',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_region',
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='agentstore',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='location.Route', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_item',
            field=models.ManyToManyField(through='location.AgentStore', to='store.Store'),
        ),
    ]
