# Generated by Django 2.1 on 2019-01-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_auto_20190125_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentstore',
            name='agent',
        ),
        migrations.AddField(
            model_name='route',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Агент'),
        ),
    ]
