# Generated by Django 2.1 on 2018-12-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20181214_1842'),
        ('store', '0002_auto_20181206_1027'),
        ('core', '0002_uploadphoto_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ReportData', verbose_name='Звіт'),
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='Торгова точка'),
        ),
    ]
