# Generated by Django 2.1 on 2018-12-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181218_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.ReportData', verbose_name='Звіт'),
        ),
    ]
