# Generated by Django 2.1 on 2018-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181218_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='file',
            field=models.ImageField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
